# Generated by Django 2.2.4 on 2022-04-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_and_ninjas_app', '0002_auto_20220423_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='dojo',
            name='state',
        ),
    ]
