# Generated by Django 2.2.4 on 2022-04-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_and_ninjas_app', '0003_auto_20220424_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='city',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dojo',
            name='state',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
    ]
