# Generated by Django 2.2.4 on 2022-04-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_and_ninjas_app', '0004_auto_20220424_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='dojo',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='dojo',
            name='state',
        ),
    ]
